### PR TITLE
retry read and write on 429

### PR DESCRIPTION
**Pull request by rbayerl**
Retry when exception is for rate limit exceeded.

### CODE REVIEW

**Review by grosser — APPROVED** [review]
little copy-pasty but seems good 👍

**Review by dcchambers — APPROVED** [review]

**Comment by dcchambers** [comment]
Strange that it's still expecting a travis-ci job to run even though the `.travis.yml` was removed from the repo.

**Comment by rbayerl** [comment]
@grosser can you merge this for me or remove travis as a required check so I can merge?

**Comment by grosser** [comment]
- trying to get eng-prod to give compute admin
- adding github-actions here https://github.com/zendesk/samson_secret_puller/pull/102

**Comment by grosser** [comment]
rebased so we get GA build

**Comment by grosser** [comment]
actually found a bug :D

**Comment by grosser** [comment]
fixing ...

**Pull request merged**
