### PR TITLE
making host_ip() respect ssl verification as it fails when dns is busted in the cluster

### PR DESCRIPTION
**Pull request by irwaters**

### CODE REVIEW

**Comment by grosser** [comment]
👍

**Comment by grosser** [comment]
can you merge/release this ?

**Comment by irwaters** [comment]
SECRET_SIDECAR_IMAGE="docker-registry.zende.sk/secret_sidecar:@sha256:be9c6e38c83805c973cfd5e59dc849b8948d383b1e0c4992bd5010196a03a8a3"

PR is open for this change.

**Comment by grosser** [comment]
force-push stable ?

**Comment by irwaters** [comment]
chef change looks to have already happened, so we should be good in theory.

**Pull request merged**
