### PR TITLE
support wildcards in key lookup

### PR DESCRIPTION
**Pull request by grosser**
@jonmoter @irwaters 

this will allow us to lookup things like MYSQL_POD_\d_SHARDS etc values without having to hardcode all possible values

### CODE REVIEW

**Comment by irwaters** [comment]
lgtm 👍 

of note, the deploy group *must* be part of the keyspace (that or global) as that's how we bind a vault instance to a given deploy group.

**Comment by jonmoter** [comment]
Could you put something in the README explaining how this works?

**Comment by grosser** [comment]
docs are in my other PR ... somehow got the branches confused :D

**Comment by grosser** [comment]
https://github.com/zendesk/samson_secret_puller/pull/17

**Comment by grosser** [comment]
reverting this since the logic will live in samson now / does not work correctly with key expansion

**Pull request merged**
