### PR TITLE
remove host-ip since it is available via downward api since 1.7 and removes nee…

### PR DESCRIPTION
**Pull request by grosser**
…d for api access

@zendesk/compute

### CODE REVIEW

**Comment by adammw** [comment]
may need to verify there's no existing apps relying on those files however..

**Comment by grosser** [comment]
sha is 940a768652734c002ba7e84d0f0949e8cd312253955e649a1adae6ccab8d977a

**Comment by adammw** [comment]
can we merge this now? 1.7+ should be well and truly everywhere by now...

**Comment by grosser** [comment]
needs a rebase and then we need to search through all code to see who uses this and migrate them ... we have a ticket for that, feel free to grab it

**Pull request merged**
